baseURL = "https://emiliosao.me/"
theme = "papermod"
languageCode = "en-us"
relativeURLs = true
canonifyURLs = true
googleAnalytics = "G-GBTND4TV5P"

[params]
  title = "emiliosao.me"
  defaultTheme = "auto"
  disableThemeToggle = true
  favicon = "favicon.png"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  hideFooter = true  # Set to false to show the footer
  noindex = true
  disableSitemap = true
  disableOpenGraph = false
  disableTwitterCards = false
  showCount = false
  mainSections = []
  homeSections = []

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  # [[menu.main]]
    # name = "CV"
    # url = "/cv/"
    # weight = 3