name: Deploy Hugo site to GitHub Pages
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy-site]
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0'
          extended: true

      - name: Build site
        run: hugo --minify --baseURL "https://emiliosao.me/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: gh-pages
          cname: emiliosao.me