name: Update Letterboxd Posts
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-posts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Requirements
        run: pip install -r scripts/requirements.txt

      - name: Run Update Script
        run: python scripts/update_letterboxd.py

      - name: Check for changes
        id: check_changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      # Setup and run Hugo if there are changes
      - name: Setup Hugo
        if: steps.check_changes.outputs.changes == 'true'
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build site
        if: steps.check_changes.outputs.changes == 'true'
        run: hugo --minify --baseURL "https://emiliosao.me/"

      # Commit both content and public directory
      - name: Commit changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add content/blog/ public/
          git commit -m "Automated update of Letterboxd posts and rebuilt site"
          git push