name: Update Letterboxd Posts
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:
jobs:
  update-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Requirements
        run: pip install -r scripts/requirements.txt

      - name: Run Update Script
        run: python scripts/update_letterboxd.py

      - name: Check for changes
        id: check_changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add content/blog/
          git commit -m "Automated update of Letterboxd posts"

      # Hugo setup and build - do this BEFORE pushing
      - name: Setup Hugo
        if: steps.check_changes.outputs.changes == 'true'
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build site
        if: steps.check_changes.outputs.changes == 'true'
        run: hugo --minify --baseURL "https://emiliosao.me/"

      # Push all changes including both content files and generated site
      - name: Push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: steps.check_changes.outputs.changes == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: gh-pages
          cname: emiliosao.me